version: '3.6'

services:
    mysql:
        image: mysql:5.7
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - "${MYSQL_DIR}:/var/lib/mysql:rw"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
        networks:
            phpdev-net:
                ipv4_address: ${NETWORK_BASE}.2

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
            - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
        ports:
            - "${RABBITMQ_PORT}:15672"
            - "${RABBITMQ_PORT2}:5672"
        volumes:
            - ${RABBITMQ_DIR}:/var/lib/rabbitmq
        networks:
            phpdev-net:
                ipv4_address: ${NETWORK_BASE}.3

    php-cliserver:
        build: ./dockerfiles/cli
        image: "dev-phpcli:v1.0"
        command: bin/console rabbitmq:consumer -l128 --no-interaction search
        depends_on:
            - mysql
            - rabbitmq
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        volumes:
            - "${HTML_DIR}:/var/www/html/${PROJECT_NAME}:rw"
            - ./dockerfiles/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
            phpdev-net:
                ipv4_address: ${NETWORK_BASE}.4
networks:
  phpdev-net:
     driver: bridge
     ipam:
        config:
            - subnet: "${NETWORK_BASE}.1/16"
